services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydb
    networks:
      - auth-master
  redis-cache:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - auth-master
networks:
  auth-master:
    driver: bridge